name: sidecar
description: Game aid for Car Wars 6th edition by Steve Jackson Games.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  appwrite: ^8.3.0
  collection: ^1.17.0
  dart_mappable: ^2.0.3
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.1
  flutter_secure_storage: ^8.0.0
  flutter_smart_dialog: ^4.9.0+3
  formz: ^0.4.1
  go_router: ^6.2.0
  intl: ^0.17.0
  logging: ^1.1.1
  meta: ^1.8.0
  morphable_shape: ^1.6.5
  oktoast: ^3.3.1
  quiver: ^3.2.1
  recase: ^4.1.0
  riverpod: ^2.3.1
  riverpod_annotation: ^2.0.1
  syncfusion_flutter_gauges: ^20.4.53
  tinycolor2: ^3.0.1
  uuid: ^3.0.7
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.3.3
  dart_mappable_builder: ^2.0.2
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  riverpod_generator: ^2.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/audiowide/Audiowide-Regular.ttf

    - family: Blazed
      fonts:
        - asset: assets/fonts/Blazed.ttf

    - family: Facon
      fonts:
        - asset: assets/fonts/Facon.ttf

global_options:
  dart_mappable_builder:
    options:
      ignoreNull: true
      discriminatorKey: classType
      generateMethods: [decode, encode, copy, stringify, equals]
      # used to specify which methods to generate (all by default)
      # generateMethods: [decode, encode, copy, stringify, equals]

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
